import {
  BarChart2,
  Bell,
  BookOpen,
  Bus,
  CalendarDays,
  ClipboardList,
  DollarSign,
  FileText,
  GraduationCap,
  MessageSquare,
  Shield,
  Users,
} from "lucide-react";

export const features = [
  {
    icon: Users,
    title: "Student Management",
    description: "Comprehensive student information system for managing enrollments, profiles, academic records, health data, and performance analytics with ease.",
    href: "/how-it-works",
    image: "/images/feature1.png",
  },
  {
    icon: GraduationCap,
    title: "Academic Management",
    description: "Streamline curriculum planning, class scheduling, examinations, grading, and report card generation in one unified system.",
    href: "/how-it-works",
    image: "/images/feature2.png",
  },
  {
    icon: ClipboardList,
    title: "Staff Management",
    description: "Efficient tools for managing staff records, attendance, leave, performance evaluation, and payroll processing.",
    href: "/how-it-works",
    image: "/images/feature3.png",
  },
  {
    icon: MessageSquare,
    title: "Communication Hub",
    description: "Integrated multi-channel messaging with email, SMS, push notifications, and a digital notice board for seamless school-wide communication.",
    href: "/how-it-works",
    image: "/images/feature4.png",
  },
  {
    icon: DollarSign,
    title: "Financial Management",
    description: "Complete fee management with online payments, automated invoicing, scholarship tracking, budget planning, and comprehensive financial reporting.",
    href: "/pricing",
    image: "/images/feature5.png",
  },
  {
    icon: Bus,
    title: "Transport Management",
    description: "Real-time GPS tracking, route optimization, driver management, vehicle maintenance, and automated parent notifications for safe student transportation.",
    href: "/how-it-works",
    image: "/images/feature6.png",
  },
  {
    icon: BookOpen,
    title: "Resource Management",
    description: "Digital library system, inventory control, facility scheduling, and asset tracking in one integrated platform.",
    href: "/how-it-works",
    image: "/images/feature7.png",
  },
  {
    icon: BarChart2,
    title: "Analytics & Reports",
    description: "Powerful analytics tools for data-driven decisions with a custom report builder, trend analysis, and interactive data visualizations.",
    href: "/how-it-works",
    image: "/images/feature8.png",
  },
  {
    icon: CalendarDays,
    title: "Attendance System",
    description: "Automated attendance tracking for students and staff with real-time dashboards and instant parent notification capabilities.",
    href: "/how-it-works",
    image: "/images/feature9.png",
  },
  {
    icon: FileText,
    title: "Examination Portal",
    description: "End-to-end examination management from scheduling and seating to result publication, with online assessment tools and secure access control.",
    href: "/how-it-works",
    image: "/images/feature10.png",
  },
  {
    icon: Bell,
    title: "Notice Board",
    description: "Digital notice board for announcements, events, and important updates with targeted distribution to specific groups or the whole school.",
    href: "/how-it-works",
    image: "/images/feature11.png",
  },
  {
    icon: Shield,
    title: "Security & Access",
    description: "Role-based access control, data encryption, audit trails, regular backups, and compliance tools for complete peace of mind.",
    href: "/how-it-works",
    image: "/images/feature12.png",
  },
];
